manifest:
  self:
    west-commands: west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/YarmanKB

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v3.2.1-patch-nrf5340-mpsl
      import: true

    - name: lumiscript
      path: modules/lumiscript
      revision: master
      url: https://github.com/YarmanKB/lumiscript
